# Rocket
print('   /\\       /\\   ')
print('  /  \\     /  \\  ')
print(' /    \\   /    \\ ')
print('+------+ +------+  ')
print('|      | |      |  ')
print('|      | |      |  ')
print('+------+ +------+  ')
print('|  TO  | |  TO  |  ')
print('|SPACE | |SPACE |  ')
print('+------+ +------+  ')
print('|      | |      |  ')
print('|      | |      |  ')
print('+------+ +------+  ')
print('   /\\       /\\   ')
print('  /  \\     /  \\  ')
print(' /    \\   /    \\ ')